"""
NormaAI Compliance Report Generator - PDF reports for gap analysis results.

Generates professional compliance reports using fpdf2:
- Gap analysis reports per framework
- Executive summary reports across multiple frameworks
- Corporate branding, requirement tables, risk matrices, recommendations

Output: PDF bytes ready for HTTP streaming or file storage.
"""

from datetime import UTC, datetime
from typing import Any

from fpdf import FPDF

# ---- Brand colours --------------------------------------------------------

_HEADER_BG = (30, 58, 95)  # #1e3a5f - corporate navy
_HEADER_TEXT = (255, 255, 255)  # white
_ACCENT = (41, 98, 168)  # #2962a8 - lighter blue for sub-headers
_ROW_EVEN = (245, 247, 250)  # light grey-blue alternating rows
_ROW_ODD = (255, 255, 255)  # white
_TEXT_DARK = (33, 37, 41)  # near-black body text
_TEXT_MUTED = (108, 117, 125)  # grey for secondary text
_GREEN = (25, 135, 84)  # compliant
_YELLOW = (255, 193, 7)  # partially compliant
_RED = (220, 53, 69)  # non-compliant
_GREY = (173, 181, 189)  # not applicable

# Priority badge colours
_PRIORITY_COLOURS = {
    "P1": (220, 53, 69),  # red - critical
    "P2": (255, 152, 0),  # orange - high
    "P3": (255, 193, 7),  # yellow - medium
    "P4": (25, 135, 84),  # green - low
}

_STATUS_COLOURS = {
    "COMPLIANT": _GREEN,
    "PARTIALLY_COMPLIANT": _YELLOW,
    "NON_COMPLIANT": _RED,
    "NOT_APPLICABLE": _GREY,
}

_STATUS_LABELS = {
    "COMPLIANT": "Compliant",
    "PARTIALLY_COMPLIANT": "Partial",
    "NON_COMPLIANT": "Non-Compliant",
    "NOT_APPLICABLE": "N/A",
}


class _NormaPDF(FPDF):
    """Thin FPDF subclass for consistent page footer."""

    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self._disclaimer = (
            "This report is generated by NormaAI using AI-assisted analysis. "
            "It does not constitute legal advice. Consult qualified professionals "
            "before making compliance decisions."
        )

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_TEXT_MUTED)
        self.cell(0, 4, self._disclaimer, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


class ComplianceReportGenerator:
    """Generate professional PDF compliance reports."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_gap_report(
        self,
        company_name: str,
        framework: str,
        gap_data: dict,
        company_profile: dict | None = None,
    ) -> bytes:
        """Generate a single-framework gap analysis PDF report.

        Args:
            company_name: Name of the assessed company.
            framework: Framework identifier (e.g. "CSRD").
            gap_data: Gap analysis results dict (see module docstring for schema).
            company_profile: Optional company profile dict for the profile section.

        Returns:
            PDF file content as bytes.
        """
        pdf = self._create_pdf()
        now = datetime.now(UTC)

        # --- Page 1: Title & Executive Summary ---
        pdf.add_page()
        self._add_header(
            pdf,
            title=f"{framework} Compliance Gap Analysis",
            subtitle=f"Prepared for {company_name}",
        )

        # Executive summary
        overall_score = gap_data.get("overall_score", 0.0)
        confidence = gap_data.get("confidence_score", 0.0)
        requirements = gap_data.get("requirements", [])
        recommendations = gap_data.get("recommendations", [])

        compliant = sum(1 for r in requirements if r.get("status") == "COMPLIANT")
        partial = sum(1 for r in requirements if r.get("status") == "PARTIALLY_COMPLIANT")
        non_compliant = sum(1 for r in requirements if r.get("status") == "NON_COMPLIANT")
        not_applicable = sum(1 for r in requirements if r.get("status") == "NOT_APPLICABLE")

        self._add_section_title(pdf, "Executive Summary")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_TEXT_DARK)

        summary_text = (
            f"This report presents the results of an automated compliance gap analysis "
            f"for {company_name} against the {framework} regulatory framework. "
            f"The analysis evaluated {len(requirements)} requirements and identified an "
            f"overall compliance score of {overall_score:.1f}%."
        )
        pdf.multi_cell(0, 5, summary_text)
        pdf.ln(4)

        # Score overview table
        self._add_score_overview(
            pdf, overall_score, confidence, compliant, partial, non_compliant, not_applicable
        )
        pdf.ln(6)

        # --- Company Profile (if provided) ---
        if company_profile:
            self._add_company_profile(pdf, company_profile)
            pdf.ln(4)

        # --- Requirements Table ---
        if requirements:
            self._add_section_title(pdf, "Detailed Requirements Assessment")
            self._add_requirement_table(pdf, requirements)
            pdf.ln(6)

        # --- Risk Summary ---
        if requirements:
            self._add_risk_summary(pdf, requirements)
            pdf.ln(6)

        # --- Recommendations ---
        if recommendations:
            self._add_recommendations(pdf, recommendations)

        # --- Generation metadata ---
        pdf.ln(8)
        self._add_section_title(pdf, "Report Metadata")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT_MUTED)
        pdf.cell(
            0, 5, f"Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT"
        )
        pdf.cell(0, 5, f"Framework: {framework}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, f"AI Confidence: {confidence:.0%}", new_x="LMARGIN", new_y="NEXT")

        return self._output_bytes(pdf)

    def generate_executive_summary(
        self,
        company_name: str,
        frameworks_data: list[dict],
    ) -> bytes:
        """Generate a multi-framework executive summary PDF.

        Args:
            company_name: Name of the assessed company.
            frameworks_data: List of gap_data dicts, one per framework.

        Returns:
            PDF file content as bytes.
        """
        pdf = self._create_pdf()
        now = datetime.now(UTC)

        pdf.add_page()
        self._add_header(
            pdf,
            title="Executive Compliance Summary",
            subtitle=f"Multi-Framework Assessment for {company_name}",
        )

        # Summary paragraph
        self._add_section_title(pdf, "Overview")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_TEXT_DARK)
        pdf.multi_cell(
            0,
            5,
            f"This executive summary consolidates compliance gap analysis results "
            f"across {len(frameworks_data)} EU regulatory frameworks for {company_name}. "
            f"Each framework was independently assessed and scored.",
        )
        pdf.ln(6)

        # Framework scores table
        self._add_section_title(pdf, "Framework Scores")
        col_widths = [50, 30, 30, 30, 30, 20]
        headers = ["Framework", "Score", "Compliant", "Partial", "Gaps", "Confidence"]
        self._draw_table_header(pdf, headers, col_widths)

        for i, fd in enumerate(frameworks_data):
            fw = fd.get("framework", "Unknown")
            score = fd.get("overall_score", 0.0)
            reqs = fd.get("requirements", [])
            conf = fd.get("confidence_score", 0.0)
            c = sum(1 for r in reqs if r.get("status") == "COMPLIANT")
            p = sum(1 for r in reqs if r.get("status") == "PARTIALLY_COMPLIANT")
            nc = sum(1 for r in reqs if r.get("status") == "NON_COMPLIANT")

            bg = _ROW_EVEN if i % 2 == 0 else _ROW_ODD
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_TEXT_DARK)
            pdf.cell(col_widths[0], 7, fw, border="LB", fill=True)
            pdf.cell(col_widths[1], 7, f"{score:.1f}%", border="B", fill=True, align="C")
            pdf.cell(col_widths[2], 7, str(c), border="B", fill=True, align="C")
            pdf.cell(col_widths[3], 7, str(p), border="B", fill=True, align="C")
            pdf.cell(col_widths[4], 7, str(nc), border="B", fill=True, align="C")
            pdf.cell(col_widths[5], 7, f"{conf:.0%}", border="RB", fill=True, align="C")
            pdf.ln()

        pdf.ln(8)

        # Per-framework highlights
        for fd in frameworks_data:
            fw = fd.get("framework", "Unknown")
            recs = fd.get("recommendations", [])
            reqs = fd.get("requirements", [])
            score = fd.get("overall_score", 0.0)

            self._add_section_title(pdf, f"{fw} - {score:.1f}% Compliance")

            # Top gaps
            gaps = [r for r in reqs if r.get("status") == "NON_COMPLIANT"]
            if gaps:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(*_RED)
                pdf.cell(0, 5, f"Critical Gaps ({len(gaps)}):", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*_TEXT_DARK)
                for g in gaps[:5]:
                    name = g.get("name", "Unknown requirement")
                    pdf.cell(5, 5, "")
                    pdf.cell(0, 5, f"- {name}", new_x="LMARGIN", new_y="NEXT")

            # Top recommendations
            if recs:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(*_ACCENT)
                pdf.cell(0, 5, "Priority Actions:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*_TEXT_DARK)
                for rec in recs[:3]:
                    action = rec.get("action", "")
                    priority = rec.get("priority", "P3")
                    pdf.cell(5, 5, "")
                    pdf.cell(0, 5, f"[{priority}] {action[:90]}", new_x="LMARGIN", new_y="NEXT")

            pdf.ln(4)

        # Metadata
        pdf.ln(4)
        self._add_section_title(pdf, "Report Metadata")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT_MUTED)
        pdf.cell(
            0, 5, f"Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT"
        )
        pdf.cell(
            0, 5, f"Frameworks assessed: {len(frameworks_data)}", new_x="LMARGIN", new_y="NEXT"
        )

        return self._output_bytes(pdf)

    # ------------------------------------------------------------------
    # Internal: PDF creation helpers
    # ------------------------------------------------------------------

    def _create_pdf(self) -> _NormaPDF:
        """Create a configured PDF instance."""
        pdf = _NormaPDF(orientation="P", unit="mm", format="A4")
        pdf.alias_nb_pages()
        pdf.set_auto_page_break(auto=True, margin=25)
        pdf.set_margins(15, 15, 15)
        return pdf

    def _output_bytes(self, pdf: _NormaPDF) -> bytes:
        """Render PDF to bytes."""
        return bytes(pdf.output())

    # ------------------------------------------------------------------
    # Internal: Section builders
    # ------------------------------------------------------------------

    def _add_header(self, pdf: _NormaPDF, title: str, subtitle: str = "") -> None:
        """Add branded header block at the top of the current page."""
        # Navy background bar
        pdf.set_fill_color(*_HEADER_BG)
        pdf.rect(0, 0, 210, 42, style="F")

        # NormaAI logo text
        pdf.set_xy(15, 8)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(*_HEADER_TEXT)
        pdf.cell(0, 10, "NormaAI", new_x="LMARGIN", new_y="NEXT")

        # Title
        pdf.set_x(15)
        pdf.set_font("Helvetica", "", 14)
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")

        # Subtitle (right-aligned date + subtitle)
        if subtitle:
            pdf.set_x(15)
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 5, subtitle)

        # Report date on the right
        now_str = datetime.now(UTC).strftime("%d %B %Y")
        pdf.set_xy(140, 32)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(55, 5, now_str, align="R")

        # Move cursor below header
        pdf.set_y(48)

    def _add_section_title(self, pdf: _NormaPDF, title: str) -> None:
        """Add a styled section title with accent underline."""
        # Check if we need a new page (at least 30mm needed for a section start)
        if pdf.get_y() > 255:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*_ACCENT)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        # Accent underline
        y = pdf.get_y()
        pdf.set_draw_color(*_ACCENT)
        pdf.set_line_width(0.4)
        pdf.line(15, y, 195, y)
        pdf.ln(3)

    def _add_score_overview(
        self,
        pdf: _NormaPDF,
        overall_score: float,
        confidence: float,
        compliant: int,
        partial: int,
        non_compliant: int,
        not_applicable: int,
    ) -> None:
        """Add a compact score overview box."""
        x_start = 15
        box_w = 43
        box_h = 22
        gap = 2.5

        boxes = [
            ("Overall Score", f"{overall_score:.1f}%", _ACCENT),
            ("Compliant", str(compliant), _GREEN),
            ("Partial", str(partial), _YELLOW),
            ("Non-Compliant", str(non_compliant), _RED),
        ]

        y = pdf.get_y()
        for i, (label, value, colour) in enumerate(boxes):
            x = x_start + i * (box_w + gap)
            # Box background
            pdf.set_fill_color(*colour)
            pdf.rect(x, y, box_w, box_h, style="F")
            # Value
            pdf.set_xy(x, y + 2)
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(box_w, 10, value, align="C")
            # Label
            pdf.set_xy(x, y + 12)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(box_w, 6, label, align="C")

        pdf.set_y(y + box_h + 4)

    def _add_company_profile(self, pdf: _NormaPDF, profile: dict) -> None:
        """Add a company profile section."""
        self._add_section_title(pdf, "Company Profile")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT_DARK)

        fields = [
            ("Company", profile.get("name", "N/A")),
            ("Sector", profile.get("sector", "N/A")),
            ("Employees", f"{profile.get('employee_count', 0):,}"),
            ("Revenue (EUR)", f"{profile.get('revenue_eur', 0):,}"),
            ("Jurisdictions", ", ".join(profile.get("jurisdictions", [])) or "N/A"),
            ("Tracked Frameworks", ", ".join(profile.get("applicable_frameworks", [])) or "N/A"),
        ]

        for label, value in fields:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(40, 5, f"{label}:", new_x="RIGHT")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 5, str(value), new_x="LMARGIN", new_y="NEXT")

    def _add_requirement_table(self, pdf: _NormaPDF, requirements: list[dict]) -> None:
        """Add a requirements table with status colours and alternating rows."""
        col_widths = [60, 28, 60, 32]
        headers = ["Requirement", "Status", "Description", "Effort"]
        self._draw_table_header(pdf, headers, col_widths)

        pdf.set_font("Helvetica", "", 8)

        for i, req in enumerate(requirements):
            name = req.get("name", "")[:40]
            status_raw = req.get("status", "NOT_APPLICABLE")
            status_label = _STATUS_LABELS.get(status_raw, status_raw)
            desc = req.get("description", "")[:55]
            effort = req.get("effort", "")
            req.get("remediation", "")

            # Calculate row height - use multi_cell for description if long
            row_h = 6

            # Check page break
            if pdf.get_y() + row_h > 270:
                pdf.add_page()
                self._draw_table_header(pdf, headers, col_widths)
                pdf.set_font("Helvetica", "", 8)

            bg = _ROW_EVEN if i % 2 == 0 else _ROW_ODD
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*_TEXT_DARK)

            y_before = pdf.get_y()

            # Requirement name
            pdf.cell(col_widths[0], row_h, name, border="LB", fill=True)

            # Status with colour dot
            status_colour = _STATUS_COLOURS.get(status_raw, _GREY)
            x_status = pdf.get_x()
            pdf.cell(col_widths[1], row_h, "", border="B", fill=True)
            # Draw colour indicator circle
            cx = x_status + 3
            cy = y_before + row_h / 2
            pdf.set_fill_color(*status_colour)
            pdf.circle(cx, cy, 1.5, style="F")
            pdf.set_fill_color(*bg)
            # Status text
            pdf.set_xy(x_status + 7, y_before)
            pdf.set_text_color(*_TEXT_DARK)
            pdf.cell(col_widths[1] - 7, row_h, status_label)
            pdf.set_xy(x_status + col_widths[1], y_before)

            # Description
            pdf.cell(col_widths[2], row_h, desc, border="B", fill=True)

            # Effort
            pdf.cell(col_widths[3], row_h, effort, border="RB", fill=True, align="C")
            pdf.ln()

    def _add_recommendations(self, pdf: _NormaPDF, recommendations: list[dict]) -> None:
        """Add prioritised recommendations section."""
        self._add_section_title(pdf, "Recommendations & Action Plan")

        if not recommendations:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.cell(0, 5, "No specific recommendations generated.", new_x="LMARGIN", new_y="NEXT")
            return

        col_widths = [15, 95, 30, 40]
        headers = ["Priority", "Action", "Effort", "Deadline"]
        self._draw_table_header(pdf, headers, col_widths)

        pdf.set_font("Helvetica", "", 8)
        for i, rec in enumerate(recommendations):
            priority = rec.get("priority", "P3")
            action = rec.get("action", "")[:70]
            effort = rec.get("effort", "")
            deadline = rec.get("deadline", "")

            if pdf.get_y() + 7 > 270:
                pdf.add_page()
                self._draw_table_header(pdf, headers, col_widths)
                pdf.set_font("Helvetica", "", 8)

            bg = _ROW_EVEN if i % 2 == 0 else _ROW_ODD
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*_TEXT_DARK)

            # Priority badge
            y_before = pdf.get_y()
            x_prio = pdf.get_x()
            pdf.cell(col_widths[0], 7, "", border="LB", fill=True)
            # Draw priority badge
            badge_colour = _PRIORITY_COLOURS.get(priority, _GREY)
            pdf.set_fill_color(*badge_colour)
            badge_x = x_prio + 2
            badge_y = y_before + 1
            pdf.rect(badge_x, badge_y, 11, 5, style="F")
            pdf.set_xy(badge_x, badge_y)
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(11, 5, priority, align="C")
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*_TEXT_DARK)
            pdf.set_font("Helvetica", "", 8)

            # Reset position for action cell
            pdf.set_xy(x_prio + col_widths[0], y_before)
            pdf.cell(col_widths[1], 7, action, border="B", fill=True)
            pdf.cell(col_widths[2], 7, effort, border="B", fill=True, align="C")
            pdf.cell(col_widths[3], 7, deadline, border="RB", fill=True, align="C")
            pdf.ln()

    def _add_risk_summary(self, pdf: _NormaPDF, requirements: list[dict]) -> None:
        """Add a text-based risk matrix / summary section."""
        self._add_section_title(pdf, "Risk Overview")

        non_compliant = [r for r in requirements if r.get("status") == "NON_COMPLIANT"]
        partial = [r for r in requirements if r.get("status") == "PARTIALLY_COMPLIANT"]
        compliant = [r for r in requirements if r.get("status") == "COMPLIANT"]

        high_effort_gaps = [r for r in non_compliant if r.get("effort", "").upper() == "HIGH"]
        [r for r in non_compliant if r.get("effort", "").upper() == "MEDIUM"]
        low_effort_gaps = [r for r in non_compliant if r.get("effort", "").upper() == "LOW"]

        # Text-based risk matrix
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_TEXT_DARK)
        pdf.cell(0, 6, "Risk Matrix (Impact vs Remediation Effort)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Draw the matrix as a simple table
        matrix_x = 25
        cell_w = 40
        cell_h = 12
        labels_y = ["HIGH", "MEDIUM", "LOW"]
        labels_x = ["Non-Compliant", "Partial", "Compliant"]

        # Y-axis label
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*_TEXT_MUTED)
        y_matrix_start = pdf.get_y()

        # Column headers
        pdf.set_xy(matrix_x + 22, y_matrix_start)
        for lx in labels_x:
            pdf.cell(cell_w, 6, lx, align="C")
        pdf.ln()

        # Build count matrix
        def _count(reqs: list, effort: str) -> int:
            return sum(1 for r in reqs if r.get("effort", "").upper() == effort)

        matrix_data = {
            "HIGH": [
                _count(non_compliant, "HIGH"),
                _count(partial, "HIGH"),
                _count(compliant, "HIGH"),
            ],
            "MEDIUM": [
                _count(non_compliant, "MEDIUM"),
                _count(partial, "MEDIUM"),
                _count(compliant, "MEDIUM"),
            ],
            "LOW": [_count(non_compliant, "LOW"), _count(partial, "LOW"), _count(compliant, "LOW")],
        }

        risk_colours = {
            (0, 0): _RED,
            (0, 1): _YELLOW,
            (0, 2): _GREEN,
            (1, 0): _RED,
            (1, 1): _YELLOW,
            (1, 2): _GREEN,
            (2, 0): _YELLOW,
            (2, 1): _GREEN,
            (2, 2): _GREEN,
        }

        for row_idx, effort_level in enumerate(labels_y):
            y_row = pdf.get_y()
            # Row label
            pdf.set_xy(matrix_x, y_row)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_TEXT_MUTED)
            pdf.cell(22, cell_h, effort_level, align="R")

            for col_idx, count in enumerate(matrix_data[effort_level]):
                colour = risk_colours.get((row_idx, col_idx), _GREY)
                # Muted background version of the colour
                bg = tuple(min(255, int(c * 0.3 + 255 * 0.7)) for c in colour)
                pdf.set_fill_color(*bg)
                pdf.set_text_color(*_TEXT_DARK)
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(cell_w, cell_h, str(count), border=1, fill=True, align="C")

            pdf.ln()

        pdf.ln(2)

        # Summary text
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT_DARK)
        total_gaps = len(non_compliant)
        if total_gaps == 0:
            pdf.multi_cell(
                0,
                5,
                "No critical compliance gaps identified. Continue monitoring for regulatory changes.",
            )
        else:
            critical = len(high_effort_gaps)
            quick_wins = len(low_effort_gaps)
            summary_parts = [f"{total_gaps} non-compliant requirement(s) identified."]
            if critical:
                summary_parts.append(
                    f"{critical} require high remediation effort (strategic priority)."
                )
            if quick_wins:
                summary_parts.append(f"{quick_wins} can be addressed with low effort (quick wins).")
            pdf.multi_cell(0, 5, " ".join(summary_parts))

    # ------------------------------------------------------------------
    # Internal: Table helpers
    # ------------------------------------------------------------------

    def _draw_table_header(self, pdf: _NormaPDF, headers: list[str], col_widths: list[int]) -> None:
        """Draw a styled table header row."""
        pdf.set_fill_color(*_ACCENT)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        for j, (header, w) in enumerate(zip(headers, col_widths, strict=False)):
            border = "LTB" if j == 0 else ("RTB" if j == len(headers) - 1 else "TB")
            pdf.cell(w, 7, header, border=border, fill=True, align="C")
        pdf.ln()
