#!/usr/bin/env python3
"""QLoRA fine-tuning of Qwen 3.5 4B for regulatory framework routing.

Trains a LoRA adapter on the dataset generated by export_training_data.py.
The adapter can be deployed via Ollama Modelfile.

Requirements:
    pip install torch transformers peft bitsandbytes datasets trl

Usage:
    python scripts/finetune_router.py
    # Then deploy:
    ollama create qwen-router -f models/Modelfile

Output:
    models/qwen-router-lora/  (LoRA adapter weights)
    models/Modelfile           (Ollama deployment config)
"""

import json
import sys
from pathlib import Path

DATA_FILE = Path(__file__).parent.parent / "data" / "router_training.jsonl"
OUTPUT_DIR = Path(__file__).parent.parent / "models" / "qwen-router-lora"
MODELFILE_PATH = Path(__file__).parent.parent / "models" / "Modelfile"

BASE_MODEL = "Qwen/Qwen3.5-4B"

# LoRA config
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

# Training config
NUM_EPOCHS = 3
BATCH_SIZE = 4
LEARNING_RATE = 2e-4
MAX_SEQ_LENGTH = 512
WARMUP_RATIO = 0.1


def load_dataset_from_jsonl(path: Path) -> list[dict]:
    """Load JSONL training data."""
    examples = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                examples.append(json.loads(line))
    return examples


def format_for_training(example: dict) -> str:
    """Format a message-based example into a single training string."""
    messages = example.get("messages", [])
    parts = []
    for msg in messages:
        role = msg["role"]
        content = msg["content"]
        if role == "system":
            parts.append(f"<|system|>\n{content}")
        elif role == "user":
            parts.append(f"<|user|>\n{content}")
        elif role == "assistant":
            parts.append(f"<|assistant|>\n{content}")
    return "\n".join(parts)


def main():
    if not DATA_FILE.exists():
        print(f"Training data not found: {DATA_FILE}")
        print("Run `python scripts/export_training_data.py` first.")
        sys.exit(1)

    try:
        import torch
        from datasets import Dataset
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            BitsAndBytesConfig,
            TrainingArguments,
        )
        from trl import SFTTrainer
    except ImportError as e:
        print(f"Missing dependency: {e}")
        print("Install: pip install torch transformers peft bitsandbytes datasets trl")
        sys.exit(1)

    print(f"Loading training data from {DATA_FILE}...")
    raw_data = load_dataset_from_jsonl(DATA_FILE)
    print(f"  {len(raw_data)} examples loaded")

    texts = [format_for_training(ex) for ex in raw_data]
    dataset = Dataset.from_dict({"text": texts})

    print(f"Loading base model: {BASE_MODEL}...")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=TARGET_MODULES,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        learning_rate=LEARNING_RATE,
        warmup_ratio=WARMUP_RATIO,
        lr_scheduler_type="cosine",
        logging_steps=10,
        save_strategy="epoch",
        fp16=True,
        gradient_accumulation_steps=2,
        report_to="none",
    )

    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        args=training_args,
        tokenizer=tokenizer,
        max_seq_length=MAX_SEQ_LENGTH,
    )

    print("Starting QLoRA fine-tuning...")
    trainer.train()

    print(f"Saving LoRA adapter to {OUTPUT_DIR}...")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    # Generate Ollama Modelfile
    MODELFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    modelfile_content = f"""\
FROM {BASE_MODEL}
ADAPTER {OUTPUT_DIR}

PARAMETER temperature 0.0
PARAMETER num_predict 512

SYSTEM \"\"\"You are a regulatory intelligence router. Analyze the user query and return JSON only.
Available frameworks: CSRD, CSDDD, AI_ACT, DORA, NIS2, TAXONOMY, GDPR.
Return: {{"frameworks": [...], "complexity": "simple|medium|complex", "entities": {{"article_refs": [], "deadlines": [], "thresholds": []}}}}\"\"\"
"""
    MODELFILE_PATH.write_text(modelfile_content, encoding="utf-8")

    print("\nDone! Deploy with:")
    print(f"  ollama create qwen-router -f {MODELFILE_PATH}")


if __name__ == "__main__":
    main()
